MovieLibrary.Web/Controllers/MovieLibraryController.cs
using MovieLibrary.Business;
using MovieLibrary.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using AutoMapper;
using MovieLibrary.Business.DTO;
using System.Net;
using log4net;
using MovieLibrary.Web.CutomFilters;
using System.IO;
using System.Configuration;
using OfficeOpenXml;
using System.Globalization;
using System.Threading;
using System.Text;
using PagedList;
using System.Diagnostics;

namespace MovieLibrary.Web.Controllers
{
    [LogAction]
    public class MovieLibraryController : Controller
    {
        //private static readonly ILog Log = LogManager.GetLogger(typeof(MovieLibraryController));

        // GET: MovieLibrary
        public ActionResult Index()
        {
            return View();
            //return RedirectToAction("Movies");
        }

        // GET: Movies
        [HttpGet]
        public ActionResult Movies()
        {

            //var movies = MoviesRepository.GetAllActiveMovies();
            //var model = Mapper.Map<List<MovieModel>>(movies);
            //return View(model);
            return View();
        }

        // GET: Movies
        [HttpGet]
        public JsonResult GetAllActiveMovies(GridMovieFilter filter)
        {
            var filterGet = Mapper.Map<GridMovieFilterDTO>(filter);
            var movies = MoviesRepository.GetAllActiveGridMovies(filterGet);
            var model = Mapper.Map<GridMovieResult>(movies);

            return Json(model, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult AddMovie()
        {
            MovieAddModel movieAdd = new MovieAddModel();
            var genres = GenresRepository.GetAllActiveGenres();
            var directors = DirectorsRepository.GetAllActiveDirectors();
            movieAdd.SelectedGenreModel.GenreCollection = Mapper.Map<List<GenreLightModel>>(genres);
            movieAdd.SelectedDirectorModel.DirectorCollection = Mapper.Map<List<DirectorLightModel>>(directors);
            return View(movieAdd);
        }

        [HttpPost]
        public ActionResult AddMovie(MovieAddModel movieModel)
        {
            if (ModelState.IsValid)
            {
                if (movieModel.ImageFile != null)
                {
                    string FileName = Path.GetFileNameWithoutExtension(movieModel.ImageFile.FileName);
                    //Get File Extension  
                    string FileExtension = Path.GetExtension(movieModel.ImageFile.FileName);
                    //Get Upload path from Web.Config file AppSettings.  
                    string UploadPath = ConfigurationManager.AppSettings["MovieImagePath"].ToString();
                    if (movieModel.ImageFile.ContentLength > 0)
                    {
                        movieModel.ImagePath = UploadPath + FileName + FileExtension;
                        movieModel.ImageTitle = FileName + FileExtension;
                    }
                }
                var data = Mapper.Map<MovieDTO>(movieModel);
                MoviesRepository.Insert(data);
                return RedirectToAction("Movies");
            }
            return View(movieModel);
        }

        public ActionResult ImportMovies()
        {
            //Read the CSV file: Get Upload path from Web.Config file AppSettings.  
            string rootPath = ConfigurationManager.AppSettings["CsvPath"].ToString();
            string fileName = @"MoviesForImport.csv";
            string path = rootPath + fileName;
            FileInfo file = new FileInfo(Path.Combine(rootPath, fileName));
            //set the formatting options
            ExcelTextFormat format = new ExcelTextFormat();
            format.Delimiter = ';';
            format.Culture = new CultureInfo(Thread.CurrentThread.CurrentCulture.ToString());
            format.Culture.DateTimeFormat.ShortDatePattern = "dd-mm-yyyy";
            format.Encoding = new UTF8Encoding();
            //create a new Excel package
            using (ExcelPackage excelPackage = new ExcelPackage())
            {
                //create a WorkSheet
                ExcelWorksheet worksheet = excelPackage.Workbook.Worksheets.Add("Movie");
                //using (var stream = file.OpenRead())
                //{
                //    excelPackage.Load(stream);
                //}
                //load the CSV data into cell A1
                worksheet.Cells["A1"].LoadFromText(file, format);
                Debug.WriteLine(worksheet.Cells["A1"].Value.ToString());

                //var worksheet = excelPackage.Workbook.Worksheets["Sheet1"];
                int totalRows = worksheet.Dimension.Rows;
                List<MovieImportModel> movieList = new List<MovieImportModel>();
                //i=1:is a file header
                for (int i = 2; i <= totalRows; i++)
                {
                    MovieImportModel mi = new MovieImportModel();
                    mi.Caption = worksheet.Cells[i, 1].Value.ToString();
                    mi.ReleaseYear = Int32.Parse(worksheet.Cells[i, 2].Value.ToString());
                    mi.SubmittedBy = worksheet.Cells[i, 3].Value.ToString();
                    mi.NumberOfAvailableCopies = Int32.Parse(worksheet.Cells[i, 4].Value.ToString());
                    mi.MovieGenres = new List<string>();
                    mi.MovieDirectors = new List<string>();
                    string[] gen = worksheet.Cells[i, 5].Value.ToString().Split(',');
                    foreach (var g in gen)
                    {
                        mi.MovieGenres.Add(g);
                    }
                    string[] dir = worksheet.Cells[i, 6].Value.ToString().Split(',');
                    foreach (var d in dir)
                    {
                        mi.MovieDirectors.Add(d);
                    }
                    movieList.Add(mi);
                }
                var data = Mapper.Map<List<MovieImportDTO>>(movieList);
                MoviesRepository.InsertRange(data);
                return RedirectToAction("Movies");
            }
        }

        //GET: MovieLibrary/MovieEdit/1
        [HttpGet]
        public ActionResult MovieEdit(int? id)
        {
            if (!id.HasValue)
            {
                return HttpNotFound();
            }
            var movie = MoviesRepository.GetActive(id.Value);
            if (movie == null)
            {
                return HttpNotFound();
            }
            var movieModel = Mapper.Map<MovieEditModel>(movie);
            var genres = GenresRepository.GetAllActiveGenres();
            var directors = DirectorsRepository.GetAllActiveDirectors();
            var directorIDs = directors.Select(d => d.DirectorID.ToString()).ToArray();
            var genreIDs = genres.Select(d => d.GenreID.ToString()).ToArray();
            movieModel.AllGenreModel.GenreCollection = Mapper.Map<List<GenreLightModel>>(genres);
            movieModel.AllDirectorModel.DirectorCollection = Mapper.Map<List<DirectorLightModel>>(directors);
            movieModel.AllDirectorModel.DirectorIDs = directorIDs;
            movieModel.AllGenreModel.GenreIDs = genreIDs;
            return View(movieModel);
        }

        //POST: MovieLibrary/MovieEdit/1
        [HttpPost]
        public ActionResult MovieEdit(MovieEditModel movieModel)
        {
            if (ModelState.IsValid)
            {
                if ((movieModel.ImageFile != null) && (movieModel.ImageFile.ContentLength > 0))
                {
                    string FileName = Path.GetFileNameWithoutExtension(movieModel.ImageFile.FileName);
                    //Get File Extension  
                    string FileExtension = Path.GetExtension(movieModel.ImageFile.FileName);
                    //Get Upload path from Web.Config file AppSettings.  
                    string UploadPath = ConfigurationManager.AppSettings["MovieImagePath"].ToString();
                    if (movieModel.ImageFile.ContentLength > 0)
                    {
                        movieModel.ImagePath = UploadPath + FileName + FileExtension;
                        movieModel.ImageTitle = FileName + FileExtension;
                    }
                }
                var data = Mapper.Map<MovieDTO>(movieModel);
                MoviesRepository.Update(data);
                return RedirectToAction("Movies");
            }
            return View(movieModel);
        }

        //POST: MovieLibrary/MovieEdit/1
        [HttpPost]
        public ActionResult MovieEditGrid(MovieModel movieModel)
        {
            if (ModelState.IsValid)
            {
                var data = Mapper.Map<MovieDTO>(movieModel);
                MoviesRepository.Update(data);
            }
            return RedirectToAction("Movies");
        }

        //GET: MovieLibrary/MovieDelete/1
        [HttpGet]
        public ActionResult MovieDelete(int? id)
        {
            if (!id.HasValue)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var result = MoviesRepository.Delete(id.Value);
            if (!result)
            {
                return HttpNotFound();
            }
            return RedirectToAction("Movies");
        }

        [HttpGet]
        public ActionResult MovieDeleteGrid(int? id)
        {
            if (!id.HasValue)
            {
                //return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                return Json(new { response = false });
            }
            var result = MoviesRepository.Delete(id.Value);
            if (!result)
            {
                // return HttpNotFound();
                return Json(new { response = result });
            }       
            //return RedirectToAction("Movies");  
            return Json(new { response = result }, JsonRequestBehavior.AllowGet);            
        }

        [HttpGet]

MovieLibrary.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Movie Library", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

MovieLibrary.Web/Views/Shared/_myLayout.cshtml
<!DOCTYPE html>

<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>@ViewBag.Title - Movie Library ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/SweetAlert2/css")
    @Styles.Render("~/Content/Icons/css")
    @Styles.Render("~/Content/Chosen/css")
    @Styles.Render("~/Content/site/css")
    @*@Styles.Render("~/Content/Datatable/css")*@

    @if (IsSectionDefined("Styles"))
    {@RenderSection("Styles", required: false)}

    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <!-- Header -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-item nav-link active" href="@Url.Action("Index", "MovieLibrary")">Home <span class="sr-only">(current)</span></a>
                <a class="nav-item nav-link" href="@Url.Action("About", "Home")">About</a>
                <a class="nav-item nav-link" href="@Url.Action("Contact", "Home")">Contact</a>
            </div>
        </div>
    </nav>
    <br />
    <!-- End of Header -->
    <!-- Content Body -->
    <div class="container-fluid body-content">
        @RenderBody()
        <hr />
    </div>
    <!-- End of Content Body -->
    <!-- Footer -->
    <footer class="page-footer font-small bg-dark text-white-50">
        <div class="footer-copyright text-center py-2">
            <small>Copyright &copy;  @DateTime.Now.Year - Movie Library ASP.NET Application</small>
        </div>
    </footer>
    <!-- End of Footer -->

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/sweetalert2")
    @Scripts.Render("~/bundles/chosen")
    @*@Scripts.Render("~/bundles/datatable")*@

    @RenderSection("scripts", required: false)
</body>
</html>